### ISSUE TITLE
No 2020 cases in Copenhagen case study

### ISSUE THREAD

**Issue by lizacoyer** [EPIET/OutbreakInvestigation#11]
In the Copenhagen case study, under 2.4.3 Incubation times, the Guide says that there are cases from the future (2020). However, we cannot find those. Perhaps these have been removed already before?

**Comment by lizacoyer** [comment]
Ah, already updated, you were faster than me :)

**Comment by AmyMikhail** [comment]
This issue is due to `lubridate::ymd_h()` misallocating the numbers to the year/month/day/hour slots because `starthour` is missing.  However it can be resolved when creating `onset_datetime` as follows:

```
onset_datetime = lubridate::ymd_h(paste(dayonset, starthour), truncate = 2))
```
With `truncate` you indicate how many digits out of the total for year/month/day/hour might be missing (in this case up to two digits for hour).
